FROM trzeci/emscripten:sdk-tag-1.37.19-64bit
MAINTAINER Matt McCormick "matt.mccormick@kitware.com"

# Revert back to "/bin/sh" as default shell
# See https://github.com/asRIA/emscripten-docker/blob/master/Dockerfile.in#L4
RUN rm /bin/sh && ln -s /bin/dash /bin/sh

ENV PATH /emsdk_portable:/emsdk_portable/sdk:/emsdk_portable/node/bin:${PATH}
